### ISSUE TITLE
Issue with LWM's Deep Storage

### ISSUE THREAD

**Issue by A-H-Z** [PeteTimesSix/SimpleSidearms#22]
Moded weapons stored in containers from the Deep Storage mod can't be equipped as sidearms, however when outisde of said containers there's no problem and they can be equipped, this issue seems to be only with moded weapons as vanilla ones can be equipped as sidearms directly from the containers with no problem.
I am using Rimmu-Nation Weapons and Prisoner Capture and Manipulation mods
![screenshot1](https://user-images.githubusercontent.com/62470741/77227422-e9c5cc80-6b88-11ea-8384-77f113d071b3.png)
![screenshot2](https://user-images.githubusercontent.com/62470741/77227424-f64a2500-6b88-11ea-9ed1-2c0944dbdec8.png)
![screenshot3](https://user-images.githubusercontent.com/62470741/77227431-0104ba00-6b89-11ea-9163-4960625d0fb2.png)

EDIT : My apologies, i should have checked this further before reporting the issue.
It isn't an issue of whether it's a moded or vanilla weapon, rather it's that i can only equip sidearms that are at the very top of the stack in the container
![screenshot4](https://user-images.githubusercontent.com/62470741/77228832-b6883b00-6b92-11ea-880f-c36120e26d79.png)
![screenshot5](https://user-images.githubusercontent.com/62470741/77228837-ba1bc200-6b92-11ea-8d32-238b8a86fb26.png)

Is this fixable on your end or should i make an issue report on Deep Storage's repo?
Sorry for asking i just created this account to report this bug, i am new to github

**Comment by lilwhitemouse** [comment]
Stupid question, but let me be sure: Open the mod settings for LWM Deep Storage and make sure that "Deep Storage right-click logic" is checked.

Next question: what's the mod order between the two?  Does changing the mod order fix the problem?  (If so, we can update our mods to specify how they should be loaded)

**Comment by A-H-Z** [comment]
Enabling the custom right click seems to have fixed it now, though i tried it before and it didn't work (maybe i had to reload the save?).
Again, my sincere apologies for not checking further, didn't intend wasting your time

**Comment by lilwhitemouse** [comment]
Hey, easy fix :)
